version: "3"

services:
  mysql:
    container_name: mysql
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=THIS_WILL_BE_YOUR_CONTAINERS_ROOT_PW
    volumes:
      - mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d/
    ports:
      - 3306:3306

  serviceregistry:
    container_name: serviceregistry
    image: svetlint/serviceregistry:latest
    depends_on:
      - mysql
    volumes:
      # dont forget to change the route of the locally available config file
      # format is <file on your local machine, (change this!!!)>:<file location inside the container (don't change this part!!!)>
      - ./core_system_config/serviceregistry.properties:/serviceregistry/application.properties
    ports:
      - 8443:8443

  authorization:
    container_name: authorization
    image: svetlint/authorization:latest
    depends_on:
      - mysql
    volumes:
      - ./core_system_config/authorization.properties:/authorization/application.properties
    ports:
      - 8445:8445

  orchestrator:
    container_name: orchestrator
    image: svetlint/orchestrator:latest
    depends_on:
      - mysql
    volumes:
      - ./core_system_config/orchestrator.properties:/orchestrator/application.properties
    ports:
      - 8441:8441

# Uncomment if you wish to use the Event Handler
#
#  eventhandler:
#    container_name: eventhandler
#    image: svetlint/eventhandler:latest
#    depends_on:
#      - mysql
#    volumes:
#      - ./core_system_config/eventhandler.properties:/eventhandler/application.properties
#    ports:
#      - 8455:8455

# Uncomment if you wish to use the Gatekeeper
#
#  gatekeeper:
#    container_name: gatekeeper
#    image: svetlint/gatekeeper:latest
#    depends_on:
#      - mysql
#    volumes:
#      - ./core_system_config/gatekeeper.properties:/gatekeeper/application.properties
#    ports:
#      - 8449:8449

# Uncomment if you wish to use the Gateway
#
#  gateway:
#    container_name: gateway
#    image: svetlint/gateway:latest
#    depends_on:
#      - mysql
#    volumes:
#      - ./core_system_config/gateway.properties:/gateway/application.properties
#    ports:
#      - 8453:8453

# Uncomment if you wish to use the Certificate Authority
#
#  certificateauthority:
#    container_name: certificateauthority
#    image: svetlint/certificateauthority:latest
#    depends_on:
#      - mysql
#    volumes:
#      - ./core_system_config/certificateauthority.properties:/certificateauthority/application.properties
#    ports:
#      - 8448:8448

# Uncomment if you wish to use the QoS Monitor
#
#  qosmonitor:
#    container_name: qosmonitor
#    image: svetlint/qosmonitor:latest
#    depends_on:
#      - mysql
#    volumes:
#      - ./core_system_config/qosmonitor.properties:/qosmonitor/application.properties
#    ports:
#      - 8451:8451

# Uncomment if you wish to use the Onboarding Controller
#
#  onboardingcontroller:
#    container_name: onboardingcontroller
#    image: svetlint/onboardingcontroller:latest
#    depends_on:
#      - mysql
#    volumes:
#      - ./core_system_config/onboardingcontroller.properties:/onboardingcontroller/application.properties
#    ports:
#      - 8435:8435

# Uncomment if you wish to use the Device Registry
#
#  deviceregistry:
#    container_name: deviceregistry
#    image: svetlint/deviceregistry:latest
#    depends_on:
#      - mysql
#    volumes:
#      - ./core_system_config/deviceregistry.properties:/deviceregistry/application.properties
#    ports:
#      - 8439:8439

# Uncomment if you wish to use the System Registry
#
#  systemregistry:
#    container_name: systemregistry
#    image: svetlint/systemregistry:latest
#    depends_on:
#      - mysql
#    volumes:
#      - ./core_system_config/systemregistry.properties:/systemregistry/application.properties
#    ports:
#      - 8437:8437

# Uncomment if you wish to use the Choreographer
#
#  choreographer:
#    container_name: choreographer
#    image: svetlint/choreographer:latest
#    depends_on:
#      - mysql
#    volumes:
#      - ./core_system_config/choreographer.properties:/choreographer/application.properties
#    ports:
#      - 8457:8457

volumes:
  mysql:
    external: true  
